### ISSUE TITLE
Running node example.js throws several undefined

### ISSUE THREAD

**Issue by xxczaki** [xxczaki/xa#6]
cc @Rekseto

**Comment by JorgeMadson** [comment]
Ok, can i  will try to fix it?

**Comment by JorgeMadson** [comment]
![captura de tela de 2018-10-25 17-28-27](https://user-images.githubusercontent.com/10890678/47528418-83e1f200-d87b-11e8-99ef-5109fd28005b.png)
This three 'warnings', (error, warn,link)  are missing a parameter, so is showing undefined after it.

**Comment by JorgeMadson** [comment]
I send a pull request.

**Comment by clayreimann** [comment]
Closed by #7
